layout: default
markdown: kramdown
exclude:
  - README
  - process-cmsdist
  - process-logs
  - process-run123-logs
  - das_queries
  - es-queries
  - data/inputs
  - data/relvaltime
  - data/unitTests
  - data/CMSSW_*
plugins:
  - jekyll-redirect-from
